/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ephemeral_keypair.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ephemeral_keypair.pb-c.h"
void   wickr__proto__ephemeral_keypair__init
                     (Wickr__Proto__EphemeralKeypair         *message)
{
  static const Wickr__Proto__EphemeralKeypair init_value = WICKR__PROTO__EPHEMERAL_KEYPAIR__INIT;
  *message = init_value;
}
size_t wickr__proto__ephemeral_keypair__get_packed_size
                     (const Wickr__Proto__EphemeralKeypair *message)
{
  assert(message->base.descriptor == &wickr__proto__ephemeral_keypair__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wickr__proto__ephemeral_keypair__pack
                     (const Wickr__Proto__EphemeralKeypair *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wickr__proto__ephemeral_keypair__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wickr__proto__ephemeral_keypair__pack_to_buffer
                     (const Wickr__Proto__EphemeralKeypair *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wickr__proto__ephemeral_keypair__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Wickr__Proto__EphemeralKeypair *
       wickr__proto__ephemeral_keypair__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Wickr__Proto__EphemeralKeypair *)
     protobuf_c_message_unpack (&wickr__proto__ephemeral_keypair__descriptor,
                                allocator, len, data);
}
void   wickr__proto__ephemeral_keypair__free_unpacked
                     (Wickr__Proto__EphemeralKeypair *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wickr__proto__ephemeral_keypair__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor wickr__proto__ephemeral_keypair__field_descriptors[3] =
{
  {
    "identifier",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Wickr__Proto__EphemeralKeypair, has_identifier),
    offsetof(Wickr__Proto__EphemeralKeypair, identifier),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ec_key",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Wickr__Proto__EphemeralKeypair, has_ec_key),
    offsetof(Wickr__Proto__EphemeralKeypair, ec_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key_signature",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Wickr__Proto__EphemeralKeypair, has_key_signature),
    offsetof(Wickr__Proto__EphemeralKeypair, key_signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wickr__proto__ephemeral_keypair__field_indices_by_name[] = {
  1,   /* field[1] = ec_key */
  0,   /* field[0] = identifier */
  2,   /* field[2] = key_signature */
};
static const ProtobufCIntRange wickr__proto__ephemeral_keypair__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor wickr__proto__ephemeral_keypair__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "wickr.proto.EphemeralKeypair",
  "EphemeralKeypair",
  "Wickr__Proto__EphemeralKeypair",
  "wickr.proto",
  sizeof(Wickr__Proto__EphemeralKeypair),
  3,
  wickr__proto__ephemeral_keypair__field_descriptors,
  wickr__proto__ephemeral_keypair__field_indices_by_name,
  1,  wickr__proto__ephemeral_keypair__number_ranges,
  (ProtobufCMessageInit) wickr__proto__ephemeral_keypair__init,
  NULL,NULL,NULL    /* reserved[123] */
};
