name: Android
on: [push, pull_request]
env:
  BUILD_TYPE: Release 
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fips: [ON, OFF]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build 
        working-directory: ${{github.workspace}}
        run: FIPS=${{matrix.fips}} OSSL_SUPPORT_UNAME=${{secrets.OSSL_FIPS_SUPPORT_UNAME}} OSSL_SUPPORT_PASS=${{secrets.OSSL_FIPS_SUPPORT_PASS}} OSSL_FIPS_URL=${{secrets.OSSL_FIPS_URL}} ./build_android_docker.sh
