name: MacOS
on: [push, pull_request]
env:
  BUILD_TYPE: Release
jobs:
  Build:
    runs-on: macos-latest
    strategy:
      matrix:
        fips: [ON, OFF]
        arch: [x86_64, arm64]
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'
      - name: Setup Ninja
        run: brew install ninja
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build \
          -DBUILD_TESTS=true \
          -DFIPS=${{matrix.fips}} \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
          -DCMAKE_OSX_ARCHITECTURES=${{matrix.arch}} \
          -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install
      - name: Build
        working-directory: ${{github.workspace}}/build
        run: make
      - if: matrix.arch == 'arm64'
        name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure
      - name: Install
        working-directory: ${{github.workspace}}/build
        run: make install
