name: Windows
on: [push, pull_request]
env:
  BUILD_TYPE: Release 
jobs:
  Build:
    runs-on: windows-2016
    strategy:
      matrix:
        fips: [ON, OFF]
    steps:
      - name: Setup cmake 
        uses: jwlawson/actions-setup-cmake@v1.12
      - name: Setup NASM
        uses: ilammy/setup-nasm@v1
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Configure CMake
        shell: pwsh
        run: |
          cmake -B ${{github.workspace}}/build `
          -DBUILD_TESTS=true `
          -DBUILD_OPENSSL=ON `
          -DFIPS=${{matrix.fips}} `
          -DOSSL_SUPPORT_UNAME="${{secrets.OSSL_FIPS_SUPPORT_UNAME}}" `
          -DOSSL_SUPPORT_PASS="${{secrets.OSSL_FIPS_SUPPORT_PASS}}" `
          -DOSSL_FIPS_URL="${{secrets.OSSL_FIPS_URL}}" `
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} `
          -G "Visual Studio 15 2017" `
          -A x64
      - name: Build 
        shell: pwsh
        working-directory: ${{github.workspace}}/build
        run: msbuild WickrCryptoC.sln /p:Configuration=Release
      - name: Test 
        shell: pwsh
        working-directory: ${{github.workspace}}/build/test/Release
        run: crypto_test.exe --ci
